# Generated by Django 5.0.4 on 2024-04-17 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servico", "0006_alter_servico_tempo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servico",
            name="imagem",
        ),
    ]
