# Generated by Django 5.0.4 on 2024-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servico", "0007_remove_servico_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="servicos/", verbose_name="Imagem"
            ),
        ),
    ]
