# Generated by Django 5.0.4 on 2024-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servico", "0009_servicoo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Servicoo",
        ),
        migrations.AlterField(
            model_name="servico",
            name="imagem",
            field=models.ImageField(
                default=True, upload_to="servicos/", verbose_name="Imagem"
            ),
        ),
    ]
