# Generated by Django 5.0.4 on 2024-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servico", "0010_delete_servicoo_alter_servico_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="imagem",
            field=models.ImageField(upload_to="servicos/", verbose_name="Imagem"),
        ),
    ]
